Create .git-blame-ignore-revs
akretion/docky-odoo-template pull request #76
Opened 2023-04-24 08:19 UTC by bealdav

Pre commit add many stuff which make git blame obscur.

Populate this file help to make things clear.

2023-04-24 08:30 UTC, florian-dacosta approved these changes

2023-04-28 08:48 UTC, hparfr approved these changes

2023-04-28 08:53 UTC, hparfr requested changes
Il faut aussi l'ajouter dans skipifexists

2023-05-03 07:18 UTC, bealdav commented
You convinced me to not add it to project skeleton.
Every dev may add it in its project.

2023-05-03 07:19 UTC, closed without merging